version: '3.8'

services:
  postgresql:
    container_name: postgresql_container
    image: bitnami/postgresql:15.4.0
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=mydatabase
      - POSTGRESQL_POSTGRES_PASSWORD=mypassword

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  document-management-service:
    image: myorg/document-management-service:latest
    container_name: document_management_service
    environment:
      - JAVA_OPTS=-Xmx50m -Xms50m
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - minio
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 50M

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge
